In [1]:
import numpy as np
list = [ '1','2','3','4','5']
array_list = np.array(object = list)

In [2]:
# Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
# to print the data types of both the variables.

In [3]:
list

['1', '2', '3', '4', '5']

In [4]:
array_list

array(['1', '2', '3', '4', '5'], dtype='<U1')

In [5]:
type(list)

list

In [6]:
type(array_list)

numpy.ndarray

In [7]:
# This code will output the data types of list_ and array_list, and you will likely see that list_ is of type list, while array_list is of type numpy.ndarray

In [8]:
# Q2. Write a code to print the data type of each and every element of both the variables list_ and
# arra_list.
# list = [ '1','2','3','4','5']
# array_list = np.array(list)

In [9]:
list = [ '1','2','3','4','5']
array_list = np.array(list)

In [10]:
list

['1', '2', '3', '4', '5']

In [11]:
array_list

array(['1', '2', '3', '4', '5'], dtype='<U1')

In [12]:
for i in list :
    print(type(i))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [13]:
for i in array_list:
    print(type(i))

<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


In [14]:
# Q3. Considering the following changes in the variable, array_list:
# array_list = np.array(object = list_, dtype = int)

In [15]:
# Define a list with string elements
list_ = ['1', '2', '3', '4', '5']
# Convert the list to a NumPy array with dtype=int
array_list = np.array(object=list_, dtype=int)

In [16]:
for i in list_:
    print(type(i))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [17]:
for i in array_list:
    print(type(i))

<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


In [18]:
# num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
# num_array = np.array(object = num_list)


# Q4. Write a code to find the following characteristics of variable, num_array:
# (i) shape
# (ii) size

In [19]:
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(num_list)

In [20]:
num_array

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
num_array.shape

(2, 3)

In [22]:
num_array.size

6

In [23]:
# Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
# creation function.
# [Hint: The size of the array will be 9 and the shape will be (3,3).]

In [24]:
z = np.zeros((3,3))

In [25]:
z

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [26]:
z.size

9

In [27]:
z.shape

(3, 3)

In [28]:
# Q6. Create an identity matrix of shape (5,5) using numpy functions?
# [Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [29]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])